### ISSUE TITLE
gulp release failing in esprima?

### ISSUE THREAD

**Issue by davidascher** [yang-wei/rd3#4]
I'm getting an odd build failure:

```
dascher-29223:rd3 dascher1$ gulp release
Loading plugins: 880ms
[13:01:36] Using gulpfile ~/src/rd3/gulpfile.js
[13:01:36] Starting 'copymisc'...
[13:01:36] Starting 'clean:build'...
[13:01:36] Finished 'clean:build' after 25 ms
[13:01:36] Starting 'minified'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: Line 13: Unexpected token {
    at throwError (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:2808:21)
    at throwUnexpected (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:2870:9)
    at expect (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:2879:13)
    at parseObjectInitialiser (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3419:17)
    at parsePrimaryExpression (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3553:20)
    at parseLeftHandSideExpressionAllowCall (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3656:61)
    at parsePostfixExpression (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3696:20)
    at parseUnaryExpression (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3763:16)
    at parseBinaryExpression (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3853:16)
    at parseConditionalExpression (/Users/dascher1/src/rd3/node_modules/esprima-fb/esprima.js:3913:16)
```

FYI:

```
dascher-29223:rd3 dascher1$ node --version
v4.4.1
dascher-29223:rd3 dascher1$ npm --version
3.5.2
```

**Comment by davidascher** [comment]
that was my error. never mind, apologies for the noise.
